### ISSUE TITLE
Research Emotion.sh style Library

### ISSUE THREAD

**Issue by kcaparas1630** [bcgov/nr-sustainment-capstone-2024#102]
## Describe the task

**As a** *QuackStack Developer* **I want** *to research Emotion.sh* **So That** *I could use that as a style component for our frontend application*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [x] Research Emotion.sh
- [x] Update Architecture Decision Log
- [x] Create a simple styled component for HealthCheck Component
- [x] Research compatibility with BC Design tokens package

## Additional context
This is going to be a research and practice.

**Comment by GDamaso** [comment]
We'll be using `@emotion/styled` with  `@bc/design-tokens`

```TypeScript
import styled from '@emotion/styled';
import * as tokens from '@bcgov/design-tokens/js';
```
I'll focus on studying the `@emotion/styled` implementation:
https://emotion.sh/docs/styled
