### ISSUE TITLE
Create Components Diagram

### ISSUE THREAD

**Issue by kcaparas1630** [bcgov/nr-sustainment-capstone-2024#108]
## Describe the task

**As a** *QuackStack Developer* **I want** *to create a Stub View Diagram* **So That** *I can illustrate the navigation paths from the landing page to other pages on the website.*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

~- [ ] Create a Stub View using mermaid~
- [x] Create diagram with draw.io
- [x] Diagram includes from APP to Farm information form components

## Additional context
- It would be creating a navigation path. Just to understand where is the landing page going in after a button click or a hyperlink click
E.G. Landing Page -> Create NMP file || Landing Page -> Load NMP File

**Comment by GDamaso** [comment]
https://github.com/bcgov/nr-sustainment-capstone-2024/wiki/BB-Components-Diagram

**Comment by kcaparas1630** [comment]
Arrows are missing so I don't know which points where. But that's an easy fix! Otherwise it looks good to me. I can understand our workflow by checking this.

![Image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/144957476/1b0b083d-8f6f-4aa1-b813-f6df5c057f7d)

**Comment by kcaparas1630** [comment]
It's showing on Github Dark mode. Should I adjust? 😆 


![Image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/144957476/174c8aa5-1da8-41c1-ad32-4f2e3a19bb78)
