### ISSUE TITLE
Create a different Header for Main Page

### ISSUE THREAD

**Issue by kcaparas1630** [bcgov/nr-sustainment-capstone-2024#140]
## Describe the task

**As a** *QuackStack Developer* **I want** *a header unique to the main page* **So That** *it is unique and precise to what the designer wants.*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [ ] A Header Component that aligns with the designer's mockups.

## Additional context
Mockup Reference:

![Image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/144957476/e35ded0d-a5de-42a6-a184-0aae401248bb)
![Image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/144957476/e88fa6f4-ebb2-4aaf-8803-953a44d52714)

**Comment by GDamaso** [comment]
Is this ready for review?

**Comment by kcaparas1630** [comment]
I removed the other pr that was a mess and created another pr with the less lines.
