### ISSUE TITLE
Implement Fields InputModule - Stage 1

### ISSUE THREAD

**Issue by GDamaso** [bcgov/nr-sustainment-capstone-2024#144]
## Describe the task

**As a** *QuackStack developer* **I want** *a Draft Fields and Soil Input Module* **So That** *I know how the Fields section would look like.*

## Acceptance Criteria

> Given I edit the Fields Form:

- [ ] When I first see the form, it asks me to add the first field automatically
- [ ] The first added field shows up in a list, with it's name, area, and optional comments.
- [ ] Each field has a name, area and comments input field
- [ ] Inputs are validated upon changes

## Additional context
- Add any other context about the task here.

**Comment by GDamaso** [comment]
I think we forgot to estimate this one...

**Comment by kcaparas1630** [comment]
We'll break this ticket down as it's a bit large
