### ISSUE TITLE
Implement Crops Form Module Draft

### ISSUE THREAD

**Issue by kcaparas1630** [bcgov/nr-sustainment-capstone-2024#213]
## Describe the task

**As a** *QuackStack Developer* **I want** *a Draft Crops Form Module* **So That** *we can add a new crops into the current field.*

## Acceptance Criteria

> Given that I've pressed new crop

- [ ] New InputModule is created
- [ ] Design follows mockups

## Additional context
- Add any other context about the task here.

**Comment by GDamaso** [comment]
@kcaparas1630 is this a duplicate?

**Comment by kcaparas1630** [comment]
This is to be deleted after I transfer my stuffs in the other tickets.
