### ISSUE TITLE
Init Express API

### ISSUE THREAD

**Issue by GDamaso** [bcgov/nr-sustainment-capstone-2024#22]
## Describe the task

**As a** *Student Developer* **I want** *an initial Express API* **So That** *API development can begin*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [x] API uses Port 3000
- [x] Express API is created with zero-configuration initial setup
- [x] The API root url is `/api/
- [x] Given I send a `get` request to `/api/health` I receive a `Status Code 200`, and message `NMP API is healthy and ready`
- [x] API Uses Typescript as language

## Additional context
- Add any other context about the task here.

**Comment by LocalNewsTV** [comment]
@GDamaso Added `using Typescript` to your requirements
