### ISSUE TITLE
Implement Calculation Module Skeleton

### ISSUE THREAD

**Issue by kcaparas1630** [bcgov/nr-sustainment-capstone-2024#245]
## Describe the task

**As a** *QuackStack Developer* **I want** *to implement a Skeleton Design for the Calculation Form* **So That** *I'll be able to export the wireframe or mockups based on the designer's idea*

## Acceptance Criteria

- [ ] Create a Design Skeleton for the Calculation Form Method

## Additional context
- Stylings will be fixed on the last sprint for cleanup

**Comment by GDamaso** [comment]
Waiting for wireframe
