### ISSUE TITLE
Revised landing page and first options

### ISSUE THREAD

**Issue by Shakespeares-spy** [bcgov/nr-sustainment-capstone-2024#64]
## Describe the task

**As a** *QuackStack Developer* **I want** *a mockup/wireframe of the landing page and first options* **So That** *I have a guide to make building these pages easier*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [x] Add and publish B.C. Government Figma library to project
- [x]  Refined mockup/wireframe improved from teammates critique of the first design
- [x]  All placeholder text removed and replaced with appropriate content
- [x] Notes/Comments detailing design choices and justifications to increase clarity

## Additional context
These exist as a guideline to help build the respective pages. They can be changed and iterated upon as needed

**Comment by Shakespeares-spy** [comment]
I'm having some issues getting the B.C. Government Figma library imported into the project. Errors appear without any message, so I'm looking into if the BC Sans font needs to be added first, among other things.

**Comment by GDamaso** [comment]
Let me know if I can help in any way 😄
