### ISSUE TITLE
Create NMP workflow diagram

### ISSUE THREAD

**Issue by GDamaso** [bcgov/nr-sustainment-capstone-2024#69]
## Describe the task

**As a** *Student Developer* **I want** *Enhance our documentation* **So That** *it includes an easy access to an activity diagram representing the NMP workflow to be replicated*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [x] Diagram is created base on NMP workflow for berries farmers (mermaid)
- [x] Diagram is added to repo wiki

## Additional context
- [NMP Diagram](https://github.com/bcgov/nr-sustainment-capstone-2024/wiki/Nutrient-Management-Program-Flowchart)

**Comment by LocalNewsTV** [comment]
@GDamaso  I see this ticket is in `Team Review` It's always handy to add on to your tickets. In this case I would include a link to that Wiki page you're hosting the work at either in the comments or `Additional Details` of the main ticket. :)

If someone on your team comes back to reference this ticket later you have a full reference to the work that was done (by link to the diagram). It's the same deal when we link a pull request to a ticket.

**Comment by LocalNewsTV** [comment]
@GDamaso Folowing up on my previous comment now that I've looked. you can put the mermaid code directly into the Wiki by wrapping it in triple backticks specifying mermaid as the language. Impressive diagram, very large :) 



![Image](https://github.com/bcgov/nr-sustainment-capstone-2024/assets/62873746/f024b40f-0608-4a60-905a-05ede8774457)
