### ISSUE TITLE
Create Testing wiki page

### ISSUE THREAD

**Issue by GDamaso** [bcgov/nr-sustainment-capstone-2024#93]
## Describe the task

**As a** *Student Developer* **I want** *Enhance our Wiki* **So That** *it contains all necessary info to understand and run out testing setup*

## Acceptance Criteria

> e.g. Given (Context), When (Action carried out), Then, (expected outcomes)

- [ ] Testing page is created with a summary
- [ ] Testing page contains info about Backend testing
- [ ] Testing page contains info about frontend testing

## Additional context
- [Testing Wiki](https://github.com/bcgov/nr-sustainment-capstone-2024/wiki/Testing)

**Comment by kcaparas1630** [comment]
Added Frontend Testing Wiki.

**Comment by kcaparas1630** [comment]
Backend Testing Wiki is done by @GDamaso ❤
